# Generated by Django 5.0.6 on 2024-07-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_state',
            new_name='shipping_county',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_zipcode',
            new_name='shipping_postcode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_city',
            new_name='shipping_town',
        ),
    ]
